In [4]:
import pandas as pd
data = pd.read_csv("Default.csv", header = 0)

In [6]:
response_var = 1
x_vec = data.iloc[:,3].as_matrix().reshape(-1,1)

In [7]:
print(x_vec)

[[  729.5264952 ]
 [  817.1804066 ]
 [ 1073.549164  ]
 [  529.2506047 ]
 [  785.6558829 ]
 [  919.5885305 ]
 [  825.5133305 ]
 [  808.6675043 ]
 [ 1161.057854  ]
 [    0.        ]
 [    0.        ]
 [ 1220.583753  ]
 [  237.045114  ]
 [  606.7423433 ]
 [ 1112.968401  ]
 [  286.2325601 ]
 [    0.        ]
 [  527.5401841 ]
 [  485.9368642 ]
 [ 1095.072735  ]
 [  228.9525496 ]
 [  954.2617928 ]
 [ 1055.956605  ]
 [  641.9843888 ]
 [  773.2117245 ]
 [  855.0085225 ]
 [  642.9997385 ]
 [ 1454.863272  ]
 [  615.7042766 ]
 [ 1119.569353  ]
 [  494.8162288 ]
 [  448.8806563 ]
 [  584.9048947 ]
 [  913.5871726 ]
 [ 1423.938917  ]
 [ 1499.724657  ]
 [  692.0341671 ]
 [  351.4534715 ]
 [  742.6276208 ]
 [  653.1184001 ]
 [  872.1386795 ]
 [  837.2626228 ]
 [ 1151.630566  ]
 [  220.5556084 ]
 [ 1690.23441   ]
 [  408.7729143 ]
 [ 1238.610321  ]
 [ 1228.30835   ]
 [  820.9192041 ]
 [  857.4851178 ]
 [  563.6181772 ]
 [ 1282.972534  ]
 [ 1505.782675  ]
 [  904.0402591 ]
 [    0.        ]
 [ 1294.49

In [8]:
x_vec1 = data.iloc[:,3].as_matrix()
print(x_vec1)

[  729.5264952    817.1804066   1073.549164     529.2506047    785.6558829
   919.5885305    825.5133305    808.6675043   1161.057854       0.             0.
  1220.583753     237.045114     606.7423433   1112.968401     286.2325601
     0.           527.5401841    485.9368642   1095.072735     228.9525496
   954.2617928   1055.956605     641.9843888    773.2117245    855.0085225
   642.9997385   1454.863272     615.7042766   1119.569353     494.8162288
   448.8806563    584.9048947    913.5871726   1423.938917    1499.724657
   692.0341671    351.4534715    742.6276208    653.1184001    872.1386795
   837.2626228   1151.630566     220.5556084   1690.23441      408.7729143
  1238.610321    1228.30835      820.9192041    857.4851178    563.6181772
  1282.972534    1505.782675     904.0402591      0.          1294.497347
  1275.550633    1536.594601    1332.522644     492.0797678    766.2343793
   690.1272462      0.          1480.655309     989.055597    1302.341835
  1044.552343       

In [9]:
y_vec = data.iloc[:,1].as_matrix().squeeze()
print(y_vec)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

In [10]:
y_vec1 = data.iloc[:,1].as_matrix()
print(y_vec1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

In [15]:
import numpy as np
from sklearn import linear_model

In [16]:
linear_regr = linear_model.LinearRegression()
logistic_regr = linear_model.LogisticRegression()

In [17]:
linear_regr.fit(x_vec,y_vec)

/usr/local/lib/python3.6/site-packages/scipy/linalg/basic.py:1018: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  warnings.warn(mesg, RuntimeWarning)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [18]:
logistic_regr.fit(x_vec,y_vec)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [19]:
from sklearn.model_selection import train_test_split

In [22]:
x_train, x_test, y_train, y_test = train_test_split(x_vec, y_vec, test_size = 0.2,
                                                    random_state = 108)

In [23]:
logistic_regr.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [24]:
score = logistic_regr.score(x_test, y_test)

In [25]:
print(score)

0.84328358209


In [28]:
x_mat = data.ix[:,range(2,5)].as_matrix().reshape(-1,3)
print(x_mat)

[[  0.00000000e+00   7.29526495e+02   4.43616251e+04]
 [  1.00000000e+00   8.17180407e+02   1.21061347e+04]
 [  0.00000000e+00   1.07354916e+03   3.17671390e+04]
 ..., 
 [  0.00000000e+00   1.75025315e+03   5.15789402e+04]
 [  0.00000000e+00   1.51560624e+03   4.86885121e+04]
 [  0.00000000e+00   2.20246240e+03   4.72872571e+04]]


In [29]:
x_train, x_text, y_train, y_test = train_test_split(x_mat, y_vec, test_size = 0.2, random_state = 108)

In [31]:
logistic_regr.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [33]:
score = logistic_regr.score(x_test, y_test)
print(score)

ValueError: X has 1 features per sample; expecting 3