In [18]:
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plt

In [5]:
import numpy as np

In [9]:
from sklearn.svm import SVC

In [8]:
import scipy

In [10]:
# Still unfamiliar concepts: Kernel, penalty parameter

In [12]:
# Lienarly separable data set
# in this case, the value of penalty parameter C obtains the infinite

In [16]:
def generate_data(n):
    np.random.seed(234)
    x1_1 = (np.random.random(int(0.5 * n))-0.5) * 100
    x2_1 = linear_func1(x1_1)

    x1_2 = (np.random.random(int(0.5 * n))-0.5) * 100
    x2_2 = linear_func(x1_2)

    y_1 = np.ones(int(0.5 * n))
    y_2 = -1 * np.ones(int(0.5 * n))
    
    x1 = np.concatenate((x1_1, x1_2))
    x2 = np.concatenate((x2_1, x2_2))
    y = np.concatenate((y_1, y_2))
    x = np.array(list(zip(x1,x2)))

In [20]:
a = [1,2,3,4,5]
b = [1,2,3,4,5]
print(list(zip(a,b)))

[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]


In [22]:
q = np.random.random(3) # printing out n random number between 0 to 1
print(q)

[ 0.63952185  0.45684365  0.49879475]


In [24]:
q = np.random.random(3) - 0.5  
print(q) # subtracting 0.5 from the list make the list randomer
# even generating number below zero

[ 0.00925268  0.31992102 -0.19228676]


In [25]:
q = (np.random.random(3) - 0.5) * 100  
print(q) 

[ 15.92782213 -18.64911092   4.46519095]


In [33]:
def linear_func(x):
    l = len(x)
    return ( 3*x + 100 + 30 * np.random.randn(l))

k = (np.random.random(3) - 0.5) * 100  
q = linear_func(k)
print(q) 

[ 152.71731575  180.50959307  127.102802  ]


In [29]:
print(np.random.randn(1)) # genearate n diff random number

[ 0.90837517]


In [30]:
print(np.random.randn(3))

[-0.64559131 -1.32361363  1.67798561]


In [31]:
print(np.random.randn(1)) 

[ 0.29918144]


In [32]:
print(len(np.random.randn(3)))

3


In [37]:
# what is numpy concatenate? 
# numpy.concatenate((a1, a2, ...), axis=0)
# Join a sequence of arrays along an existing axis.

In [49]:

k_l = np.array([1,2])
m_l = np.array([4,3,4])

n = np.concatenate(k_l, m_l)
print(n)

TypeError: only integer scalar arrays can be converted to a scalar index

In [50]:
# oh, I need to know the difference between array and list in python.