In [1]:
import numpy
A = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13 ,14 ,15, 16]])
print(A)
slice_Y_equal_size = numpy.split(A, 2, axis = 0)
    print(slice_Y_equal_size[0])
    print(slice_Y_equal_size[1])
slice_X_different_sizes = numpy.split(A, [2, 3], axis = 1)
    print(slice_X_different_sizes[0])
    print(slice_X_different_sizes[1])
    print(slice_X_different_sizes[2])

IndentationError: unexpected indent (<ipython-input-1-e40b21a971b6>, line 2)

In [4]:
import numpy
A = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13 ,14 ,15, 16]])
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [6]:
slice_Y_equal_size = numpy.split(A, 2, axis = 0)
print(slice_Y_equal_size[0])
    

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
print(slice_Y_equal_size[1])

[[ 9 10 11 12]
 [13 14 15 16]]


In [8]:
slice_X_different_sizes = numpy.split(A, [2, 3], axis = 1)
   
print(slice_X_different_sizes[1])
    

[[ 3]
 [ 7]
 [11]
 [15]]
