In [2]:
from sklearn import datasets

In [5]:
from sklearn.datasets import load_iris

In [6]:
data = load_iris()

In [7]:
print(data)

{'data': array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
 

In [8]:
from sklearn.linear_model import LogisticRegression
import numpy as np

In [10]:
data = datasets.load_iris(return_X_y = True)

In [11]:
print(data)

(array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 

In [13]:
data2 = datasets.load_iris(return_X_y = False)

In [14]:
print(data2)

{'data': array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
 

In [20]:
iris = datasets.load_iris(return_X_y = True) # (data,target) 
print(iris[0]) # data (X: x1, x2, x3)
print(iris[1]) # target (y)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [16]:
def binary_classification(X, binary_labels):
    lr = LogisticRegression()
    lr.fit(X, )

SyntaxError: unexpected EOF while parsing (<ipython-input-16-4abb2ac782a4>, line 1)

In [22]:
X = iris[0] # Data   X: Four features
y = iris[1] # Target y: Three classes
lr = LogisticRegression()
a = lr.fit(X,y)
print(a)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)


In [26]:
import matplotlib
%matplotlib inline

In [27]:
import matplotlib.pyplot as plt

In [28]:
import numpy as np

In [29]:
import pandas as pd

In [31]:
data = pd.read_csv("Default.csv")

In [33]:
response_var = 1
y_vec = data.ix[:,response_var]

In [34]:
print(y_vec)

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
      ..
636    1
637    1
638    1
639    1
640    1
641    1
642    1
643    1
644    1
645    1
646    1
647    1
648    1
649    1
650    1
651    1
652    1
653    1
654    1
655    1
656    1
657    1
658    1
659    1
660    1
661    1
662    1
663    1
664    1
665    1
Name: default, Length: 666, dtype: int64


In [35]:
x_vec = data.ix[:, 3]

In [36]:
print(x_vec)

0       729.526495
1       817.180407
2      1073.549164
3       529.250605
4       785.655883
5       919.588530
6       825.513330
7       808.667504
8      1161.057854
9         0.000000
10        0.000000
11     1220.583753
12      237.045114
13      606.742343
14     1112.968401
15      286.232560
16        0.000000
17      527.540184
18      485.936864
19     1095.072735
20      228.952550
21      954.261793
22     1055.956605
23      641.984389
24      773.211725
25      855.008522
26      642.999738
27     1454.863272
28      615.704277
29     1119.569353
          ...     
636    1800.641733
637    1547.995445
638    2095.114817
639    1538.015603
640    1815.174112
641    2073.782846
642     961.732662
643    1825.970599
644    1658.967689
645    1506.191848
646    1719.255655
647    2046.639515
648    1726.479610
649    1666.113834
650     959.159213
651     652.397134
652    1502.186739
653    2128.795992
654    1530.551479
655    1698.826142
656    1867.308569
657    1975.

In [41]:
from sklearn import linear_model
regr_linear = linear_model.LinearRegression()
regr_linear.fit(x_vec, y_vec)

/usr/local/lib/python3.6/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


ValueError: Found input variables with inconsistent numbers of samples: [1, 666]

In [50]:
x_vec = data.ix[:, 3].as_matrix().reshape(-1,1)

In [51]:
print(x_vec)

[[  729.5264952 ]
 [  817.1804066 ]
 [ 1073.549164  ]
 [  529.2506047 ]
 [  785.6558829 ]
 [  919.5885305 ]
 [  825.5133305 ]
 [  808.6675043 ]
 [ 1161.057854  ]
 [    0.        ]
 [    0.        ]
 [ 1220.583753  ]
 [  237.045114  ]
 [  606.7423433 ]
 [ 1112.968401  ]
 [  286.2325601 ]
 [    0.        ]
 [  527.5401841 ]
 [  485.9368642 ]
 [ 1095.072735  ]
 [  228.9525496 ]
 [  954.2617928 ]
 [ 1055.956605  ]
 [  641.9843888 ]
 [  773.2117245 ]
 [  855.0085225 ]
 [  642.9997385 ]
 [ 1454.863272  ]
 [  615.7042766 ]
 [ 1119.569353  ]
 [  494.8162288 ]
 [  448.8806563 ]
 [  584.9048947 ]
 [  913.5871726 ]
 [ 1423.938917  ]
 [ 1499.724657  ]
 [  692.0341671 ]
 [  351.4534715 ]
 [  742.6276208 ]
 [  653.1184001 ]
 [  872.1386795 ]
 [  837.2626228 ]
 [ 1151.630566  ]
 [  220.5556084 ]
 [ 1690.23441   ]
 [  408.7729143 ]
 [ 1238.610321  ]
 [ 1228.30835   ]
 [  820.9192041 ]
 [  857.4851178 ]
 [  563.6181772 ]
 [ 1282.972534  ]
 [ 1505.782675  ]
 [  904.0402591 ]
 [    0.        ]
 [ 1294.49

In [48]:
y_vec = data.ix[:,1].as_matrix().squeeze()

In [49]:
print(y_vec)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

#### linear = linear_model.LinearRegression()
linear.fit(x_vec,y_vec)

In [53]:
logistic = linear_model.LogisticRegression()
logistic.fit(x_vec,y_vec)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [54]:
def binary_classification(X, binary_label):
    lr = LogisticRegression()
    lr.fit(X, binary_label)
    predict_p = lr.predict_proba(X)
    return predict_p

In [55]:
X = iris[0]
y = iris[1]
x1 = X.ix[:,1].as_matrix().reshape(-1,1)
x2 = X.ix[:,2].as_matrix().reshape(-1,1)
x3 = X.ix[:,3].as_matrix().reshape(-1.1)
def multiclass_classification(X,y):
    
    a = binary_classification(x1, y)
    b = bianry_classification(x2, y)
    c = binary_classification(x3, y)
    out = max(a,b,c).index()
    return out
    
    

AttributeError: 'numpy.ndarray' object has no attribute 'ix'