In [9]:
import numpy
A = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13 ,14 ,15, 16]])
print(A)
slice_Y_equal_size = numpy.split(A, 2, axis = 0)
print(slice_Y_equal_size[0])
print(slice_Y_equal_size[1])
slice_X_different_sizes = numpy.split(A, [2, 3], axis = 1)
print(slice_X_different_sizes[0])
print(slice_X_different_sizes[1])
print(slice_X_different_sizes[2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]
[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 3]
 [ 7]
 [11]
 [15]]
[[ 4]
 [ 8]
 [12]
 [16]]


In [4]:
import numpy
A = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13 ,14 ,15, 16]])
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [6]:
slice_Y_equal_size = numpy.split(A, 2, axis = 0)
print(slice_Y_equal_size[0])
    

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
print(slice_Y_equal_size[1])

[[ 9 10 11 12]
 [13 14 15 16]]


In [8]:
slice_X_different_sizes = numpy.split(A, [2, 3], axis = 1)
   
print(slice_X_different_sizes[1])
    

[[ 3]
 [ 7]
 [11]
 [15]]


In [17]:
import numpy as np
M = np.array([[1,2,3],[2,3,4],[4,5,6]])
print(M)

[[1 2 3]
 [2 3 4]
 [4 5 6]]


In [18]:
slice_M_equally = np.split(M, 3, axis = 0)

In [20]:
print (slice_M_equally)

[array([[1, 2, 3]]), array([[2, 3, 4]]), array([[4, 5, 6]])]


In [21]:
slice_M_dp = np.split(M,[2], axis = 1)

In [24]:
print (slice_M_dp)

[array([[1, 2],
       [2, 3],
       [4, 5]]), array([[3],
       [4],
       [6]])]
