In [1]:
# tools

In [2]:
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from sklearn.svm import SVC  # SVC stands for : Support Vector Classification
import elice_utils


# Functions linear_func1, linear_func2, and generate_data is used to generate random datapoints. You do not need to change this function
def linear_func1(x):
    l = len(x)
    return (3*x + 100 + 30 * np.random.randn(l))

def linear_func2(x):
    l = len(x)
    return (3*x - 100 + 30 * np.random.randn(l))

def generate_data(n):
    np.random.seed(328183)
    x1_1 = (np.random.random(int(0.5 * n)) - 0.5) * 100
    x2_1 = linear_func1(x1_1)
    x1_2 = (np.random.random(int(0.5 * n)) - 0.5) * 100
    x2_2 = linear_func2(x1_2)
    y_1 = np.ones(int(0.5 * n))
    y_2 = -1 * np.ones(int(0.5 * n))

    x1 = np.concatenate((x1_1, x1_2))
    x2 = np.concatenate((x2_1, x2_2))
    y = np.concatenate((y_1, y_2))
    X = np.array(list(zip(x1, x2)))

    return (X, y)

def svm(X, y):
    clf = SVC(C=np.inf, kernel='linear')
    clf.fit(X, y)
    return (clf)

def draw(X, y, clf):
    filename = "simplest_svm.png"

    ###These are to make the figure clearer. You don't need to change this part.
    plt.gca().spines['top'].set_visible(False)
    plt.gca().spines['right'].set_visible(False)
    plt.gca().spines['bottom'].set_color('yellow') # fancy gca, is for drawing a line box? 
    plt.gca().spines['left'].set_color('green') # fancy name, spine, just y-axis line
    plt.xlabel('x1', fontsize=20, color='red'); plt.ylabel('x2', fontsize=20, color='red') # x,y- axis large title X1 and X2
    plt.tick_params(axis='x', colors='blue')    # x-axis value itself
    plt.tick_params(axis='y', colors='blue')    # y-axis value itslef

    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    #h = 0.5  # step size in the mesh
    xx, yy = np.meshgrid(np.arange(x_min, x_max, 50), np.arange(y_min, y_max, 10)) # WTF?.... what does mesh step size do in thi model? 
    
    Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)
    plt.contour(xx, yy, Z, colors='black', alpha=0.6)
    plt.scatter(X[:, 0], X[:, 1], c = ['pink' if yy == 1 else '#78A5A3' for yy in y], edgecolor='none', s=30)

    plt.savefig(filename)
    elice_utils.send_image(filename)

    plt.close()

if __name__ == '__main__':
    X, y = generate_data(100)
    clf = svm(X, y)
    draw(X, y, clf) 

ModuleNotFoundError: No module named 'elice_utils'

In [3]:
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from sklearn.svm import SVC  # SVC stands for : Support Vector Classification
import elice_utils


# Functions linear_func1, linear_func2, and generate_data is used to generate random datapoints. You do not need to change this function
def linear_func1(x):
    l = len(x)
    return (3*x + 100 + 30 * np.random.randn(l))

def linear_func2(x):
    l = len(x)
    return (3*x - 100 + 30 * np.random.randn(l))

def generate_data(n):
    np.random.seed(328183)
    x1_1 = (np.random.random(int(0.5 * n)) - 0.5) * 100
    x2_1 = linear_func1(x1_1)
    x1_2 = (np.random.random(int(0.5 * n)) - 0.5) * 100
    x2_2 = linear_func2(x1_2)
    y_1 = np.ones(int(0.5 * n))
    y_1[-1 * n//50:] = -1.
    y_2 = -1 * np.ones(int(0.5 * n))
    y_2[-1 * n//50:] = 1.

    x1 = np.concatenate((x1_1, x1_2))
    x2 = np.concatenate((x2_1, x2_2))
    y = np.concatenate((y_1, y_2))
    X = np.array(list(zip(x1, x2)))

    return (X, y)

def svm(X, y):
    clf = SVC(C=0.1, kernel='linear')
    clf.fit(X, y)
    return (clf)

def draw(X, y, clf):
    filename = "simplest_svm.png"

    ###These are to make the figure clearer. You don't need to change this part.
    plt.gca().spines['top'].set_visible(False)
    plt.gca().spines['right'].set_visible(False)
    plt.gca().spines['bottom'].set_color('#999999')
    plt.gca().spines['left'].set_color('#999999')
    plt.xlabel('x1', fontsize=20, color='#555555'); plt.ylabel('x2', fontsize=20, color='#555555')
    plt.tick_params(axis='x', colors='#777777')
    plt.tick_params(axis='y', colors='#777777')    

    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    h = 0.3  # step size in the mesh
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))
    
    Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)
    plt.contour(xx, yy, Z, colors='#CE5A57', alpha=0.6)
    plt.scatter(X[:, 0], X[:, 1], c = ['red' if yy == 1 else 'blue' for yy in y], edgecolor='none', s=30)

    plt.savefig(filename)
    elice_utils.send_image(filename)

    plt.close()

if __name__ == '__main__':
    X, y = generate_data(100)
    clf = svm(X, y)
    draw(X, y, clf) 

ModuleNotFoundError: No module named 'elice_utils'

In [4]:
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from sklearn.svm import SVC  # SVC stands for : Support Vector Classification
import elice_utils


# Functions linear_func1, linear_func2, and generate_data is used to generate random datapoints. You do not need to change this function
def nonlinear_func1(x):
    l = len(x)
    return (0.1 * pow(x, 3) + 0.5 * pow(x, 2) + 0.5 * x + 1000 + 3000 * np.random.random(l))

def nonlinear_func2(x):
    l = len(x)
    return (0.1 * pow(x, 3) + 0.2 * pow(x, 2) - 0.5 * x - 1000 - 3000 * np.random.random(l))

def generate_data(n):
    np.random.seed(32840091)

    x1_1 = (np.random.random(int(0.5 * n)) - 0.5) * 100
    x2_1 = nonlinear_func1(x1_1)
    x1_2 = (np.random.random(int(0.5 * n)) - 0.5) * 100
    x2_2 = nonlinear_func2(x1_2)
    y_1 = np.ones(int(0.5 * n))
    y_2 = -1 * np.ones(int(0.5 * n))

    x1 = np.concatenate((x1_1, x1_2))
    x2 = np.concatenate((x2_1, x2_2))
    y = np.concatenate((y_1, y_2))
    X = np.array(list(zip(x1, x2)))

    return (X, y)

def svm(X, y):
    clf = SVC(kernel='rbf', C=np.inf, gamma=1e-8)
    clf.fit(X, y)
    return (clf)

def draw(X, y, clf):
    filename = "nonlinear_svm.png"

    ###These are to make the figure clearer. You don't need to change this part.
    plt.gca().spines['top'].set_visible(False)
    plt.gca().spines['right'].set_visible(False)
    plt.gca().spines['bottom'].set_color('#999999')
    plt.gca().spines['left'].set_color('#999999')
    plt.xlabel('x1', fontsize=20, color='#555555'); plt.ylabel('x2', fontsize=20, color='#555555')
    plt.tick_params(axis='x', colors='#777777')
    plt.tick_params(axis='y', colors='#777777')

    x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
    y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
    h = 0.5  # step size in the mesh
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))
    
    Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)
    plt.contour(xx, yy, Z, colors='#CE5A57', alpha=0.25)
    plt.scatter(X[:, 0], X[:, 1], c = ['#444C5C' if yy == 1 else '#78A5A3' for yy in y], edgecolor='none', s=30)

    plt.savefig(filename)
    elice_utils.send_image(filename)

    plt.close()

if __name__ == '__main__':
    X, y = generate_data(100)
    clf = svm(X, y)
    draw(X, y, clf) 

ModuleNotFoundError: No module named 'elice_utils'

In [5]:
# Logistics

In [6]:
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model
import pandas as pd
import elice_utils


def main():
    data = pd.read_csv("./data/Default.csv", header=0)
    response_var = 1
    y_vec = data.ix[:, response_var].as_matrix().squeeze()
    x_vec = data.ix[:, 3].as_matrix().reshape(-1, 1) # make vertical

    one_var_default(x_vec, y_vec)


def one_var_default(x_vec, y_vec):
    filename = "default_logit_fig.png"

    regr_linear = linear_model.LinearRegression()
    regr_linear.fit(x_vec, y_vec)

    regr_logistic = linear_model.LogisticRegression()
    regr_logistic.fit(x_vec, y_vec)

    print("Independent variable: {}".format("Balance"))
    print("Coefficients: {}".format(regr_logistic.coef_))
    print("Intercept: {}".format(regr_logistic.intercept_))

    x_minmax = np.arange(x_vec.min(), x_vec.max()).reshape(-1, 1)
    plt.plot(x_vec, regr_linear.predict(x_vec), color='blue', linewidth=3)
    plt.plot(x_minmax, regr_logistic.predict_proba(x_minmax)[:, 1], color='red', linewidth=3)
    plt.scatter(x_vec, y_vec, color='black')

    plt.xlim((x_vec.min(), x_vec.max()))

    plt.savefig(filename)
    elice_utils.send_image(filename)

    plt.close()


if __name__ == "__main__":
    main()


ModuleNotFoundError: No module named 'pandas'

In [7]:
from sklearn import linear_model
import pandas as pd
from sklearn.model_selection import train_test_split


def main():
    data = pd.read_csv("./data/Default.csv", header=0)
    response_var = 1
    y_vec = data.ix[:, response_var].as_matrix().squeeze()
    x_vec = data.ix[:, 3].as_matrix().reshape(-1, 1)

    one_var_default_pred(x_vec, y_vec)


def one_var_default_pred(x_vec, y_vec, rs = 120):
    x_train, x_test, y_train, y_test = train_test_split(x_vec, y_vec, test_size=0.25, random_state = rs)
    regr_logistic = linear_model.LogisticRegression()

    regr_logistic.fit(x_train, y_train)

    score = regr_logistic.score(x_test, y_test)

    print("Independent variable: {}".format("Balance"))
    print("Coefficients: {}".format(regr_logistic.coef_))
    print("Intercept: {}".format(regr_logistic.intercept_))
    print("Accuracy: {}".format(score))


if __name__ == "__main__":
    main()


ModuleNotFoundError: No module named 'pandas'

In [8]:
from sklearn import linear_model
import pandas as pd
from sklearn.model_selection import train_test_split


def main():
    data = pd.read_csv("./data/Default.csv", header=0)
    response_var = 1
    y_vec = data.ix[:, response_var].as_matrix().squeeze()
    x_mat = data.ix[:, range(2, 5)].as_matrix().reshape(-1, 3)

    multi_var_default(x_mat, y_vec)


def multi_var_default(x_mat, y_vec, rs=108):
    x_train, x_test, y_train, y_test = train_test_split(x_mat, y_vec, test_size=0.2, random_state=rs)

    regr_logistic = linear_model.LogisticRegression()

    regr_logistic.fit(x_train, y_train)

    score = regr_logistic.score(x_test, y_test)

    print("Indepedent variables: {}".format("ALL"))
    print("Coefficients: {}".format(regr_logistic.coef_))
    print("Intercept: {}".format(regr_logistic.intercept_))
    print("Accuracy: {}".format(score))


if __name__ == "__main__":
    main()


ModuleNotFoundError: No module named 'pandas'

In [9]:
def main():
    data = pd.read_csv("./data/Default.csv", header=0)
    response_var = 1
    y_vec = data.ix[:, response_var].as_matrix().squeeze()#y 종속 dep 파산여부 0,1 이라고 한 게 아니고 그냥 1번째 꺼 내놓으라는 뜻
    x_vec = data.ix[:, 3].as_matrix().reshape(-1, 1) #x 독립 ind 잔고

    one_var_default(x_vec, y_vec)

In [10]:
# accuracy score
def one_var_default_pred(x_vec, y_vec, rs = 120):
    x_train, x_test, y_train, y_test = train_test_split(x_vec, y_vec, test_size=0.25, random_state = rs)
    regr_logistic = linear_model.LogisticRegression()

    regr_logistic.fit(x_train, y_train)

    score = regr_logistic.score(x_test, y_test)


In [13]:
import pandas as pd
df = pd.DataFrame({'A':[1,2,3],
                   'B':[4,5,6],
                   'C':[7,8,9],
                   'D':[1,3,5],
                   'E':[5,3,6],
                   'F':[7,4,3]})
print(df)

   A  B  C  D  E  F
0  1  4  7  1  5  7
1  2  5  8  3  3  4
2  3  6  9  5  6  3


In [14]:
print(df.ix[:, 1])

0    4
1    5
2    6
Name: B, dtype: int64


/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


In [15]:
print(df.ix[:, 1].as_matrix().squeeze())

[4 5 6]


In [32]:
print(df.ix[:, 3].reshape(-1,3))

[[1 3 5]]


/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  """Entry point for launching an IPython kernel.


In [18]:
print(df.ix[:, 3].as_matrix().reshape(1,-1))

[[1 3 5]]


In [33]:
print(df.ix[:, 3])

0    1
1    3
2    5
Name: D, dtype: int64


In [19]:
print(df.ix[:, 3].as_matrix().reshape(-1,1))

[[1]
 [3]
 [5]]


In [20]:
#data = pd.read_csv("", header=0)
    response_var = 1
    y_vec = data.ix[:, response_var].as_matrix().squeeze()
    x_mat = data.ix[:, range(2, 5)].as_matrix().reshape(-1, 3)

IndentationError: unexpected indent (<ipython-input-20-103a208c626f>, line 2)

In [21]:
def multi_var_default(x_mat, y_vec, rs=108):
    x_train, x_test, y_train, y_test = train_test_split(x_mat, y_vec, test_size=0.2, random_state=rs)

    regr_logistic = linear_model.LogisticRegression()

    regr_logistic.fit(x_train, y_train)

    score = regr_logistic.score(x_test, y_test)


In [22]:
data = pd.read_csv("Default.csv", header=0)

In [23]:
print(data)

     Unnamed: 0  default  student      balance        income
0             1        0        0   729.526495  44361.625070
1             2        0        1   817.180407  12106.134700
2             3        0        0  1073.549164  31767.138950
3             4        0        0   529.250605  35704.493940
4             5        0        0   785.655883  38463.495880
5             6        0        1   919.588530   7491.558572
6             7        0        0   825.513330  24905.226580
7             8        0        1   808.667504  17600.451340
8             9        0        0  1161.057854  37468.529290
9            10        0        0     0.000000  29275.268290
10           11        0        1     0.000000  21871.073090
11           12        0        1  1220.583753  13268.562220
12           13        0        0   237.045114  28251.695340
13           14        0        0   606.742343  44994.555850
14           15        0        0  1112.968401  23810.174050
15           16        0

In [24]:
y_vec = data.ix[:,1]
print(y_vec)

0      0
1      0
2      0
3      0
4      0
5      0
6      0
7      0
8      0
9      0
10     0
11     0
12     0
13     0
14     0
15     0
16     0
17     0
18     0
19     0
20     0
21     0
22     0
23     0
24     0
25     0
26     0
27     0
28     0
29     0
      ..
636    1
637    1
638    1
639    1
640    1
641    1
642    1
643    1
644    1
645    1
646    1
647    1
648    1
649    1
650    1
651    1
652    1
653    1
654    1
655    1
656    1
657    1
658    1
659    1
660    1
661    1
662    1
663    1
664    1
665    1
Name: default, Length: 666, dtype: int64


/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  """Entry point for launching an IPython kernel.


In [25]:
y_vec1 = data.ix[:,1].as_matrix()
print(y_vec1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

In [26]:
y_vec2 = data.ix[:,1].as_matrix().squeeze()
print(y_vec2)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

In [27]:
y_vec1 == y_vec2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [28]:
x_mat = data.ix[:, range(2, 5)]
print(x_mat)

     student      balance        income
0          0   729.526495  44361.625070
1          1   817.180407  12106.134700
2          0  1073.549164  31767.138950
3          0   529.250605  35704.493940
4          0   785.655883  38463.495880
5          1   919.588530   7491.558572
6          0   825.513330  24905.226580
7          1   808.667504  17600.451340
8          0  1161.057854  37468.529290
9          0     0.000000  29275.268290
10         1     0.000000  21871.073090
11         1  1220.583753  13268.562220
12         0   237.045114  28251.695340
13         0   606.742343  44994.555850
14         0  1112.968401  23810.174050
15         0   286.232560  45042.413040
16         0     0.000000  50265.312350
17         1   527.540184  17636.539620
18         0   485.936864  61566.106120
19         0  1095.072735  26464.631390
20         0   228.952550  50500.182200
21         0   954.261793  32457.509080
22         0  1055.956605  51317.883080
23         0   641.984389  30466.103260


In [29]:
x_mat1 = data.ix[:, range(2, 5)].as_matrix()
print(x_mat1)

[[  0.00000000e+00   7.29526495e+02   4.43616251e+04]
 [  1.00000000e+00   8.17180407e+02   1.21061347e+04]
 [  0.00000000e+00   1.07354916e+03   3.17671390e+04]
 ..., 
 [  0.00000000e+00   1.75025315e+03   5.15789402e+04]
 [  0.00000000e+00   1.51560624e+03   4.86885121e+04]
 [  0.00000000e+00   2.20246240e+03   4.72872571e+04]]


In [30]:
x_mat2 = data.ix[:, range(2, 5)].as_matrix().reshape(-1, 3)
print(x_mat2)

[[  0.00000000e+00   7.29526495e+02   4.43616251e+04]
 [  1.00000000e+00   8.17180407e+02   1.21061347e+04]
 [  0.00000000e+00   1.07354916e+03   3.17671390e+04]
 ..., 
 [  0.00000000e+00   1.75025315e+03   5.15789402e+04]
 [  0.00000000e+00   1.51560624e+03   4.86885121e+04]
 [  0.00000000e+00   2.20246240e+03   4.72872571e+04]]
