In [2]:
import numpy as np
A = np.array([[1,4,5,8], [2,1,7,3], [5,4,5,9]])

    
B = A.reshape((6,2))
print(B)  

[[1 4]
 [5 8]
 [2 1]
 [7 3]
 [5 4]
 [5 9]]


In [4]:
add_b = np.array([[2,2],[5,3]])
B_Y = np.concatenate((B,add_b),axis = 0)
print (B_Y)

[[1 4]
 [5 8]
 [2 1]
 [7 3]
 [5 4]
 [5 9]
 [2 2]
 [5 3]]


In [6]:
slice_B_two = np.split(B_Y,2,axis=0)
print (slice_B_two[0])

[[1 4]
 [5 8]
 [2 1]
 [7 3]]


In [9]:
# Stats with Numpy
A = np.array([1,2,3])
print(np.sum(A))

6


In [10]:
add_A = A+3
print(add_A)

[4 5 6]


In [11]:
mul_A = A * 3
print(mul_A)

[3 6 9]


In [12]:
 # Thousands of things affect to be eventually close to somebody. So do not blame yourself. 
    # Your distinctive characteristic is just one of those, the thousands.

    
B = np.array([13,32,45,678,45])
print(np.mean(B))
print(np.median(B))

162.6
45.0


In [13]:
print(np.std(B))

257.966354395


In [14]:
print(np.var(B))

66546.64


In [15]:
A = np.array([[1,4,5,8], [2,1,7,3], [5,4,5,9]])

B = A.reshape((6, 2))
B = np.concatenate((B, np.array([[2, 2], [5, 3]])), axis = 0)
(C, D) = np.split(B, 2, axis = 0)
E = np.concatenate((C, D), axis = 1)
print(E)

[[1 4 5 4]
 [5 8 5 9]
 [2 1 2 2]
 [7 3 5 3]]


In [16]:
E_mean = np.mean(E)
print(E_mean)

4.125


In [17]:
E_std=np.std(E)
print(E_std)

2.31503239718


In [22]:
norm_E=np.array((E-(E_mean))/(E_std))
print (norm_E)

[[-1.34987312 -0.05399492  0.37796447 -0.05399492]
 [ 0.37796447  1.67384267  0.37796447  2.10580206]
 [-0.91791372 -1.34987312 -0.91791372 -0.91791372]
 [ 1.24188327 -0.48595432  0.37796447 -0.48595432]]


In [23]:
print(np.sum(norm_E))

0.0


In [24]:
print(np.sum(E))

66


In [25]:
# Normalizing to make the total sum of the components be 1
sum_E = np.sum(E)
print(sum_E)

66


In [26]:
div_E=np.array(E / sum_E)
print(div_E)

[[ 0.01515152  0.06060606  0.07575758  0.06060606]
 [ 0.07575758  0.12121212  0.07575758  0.13636364]
 [ 0.03030303  0.01515152  0.03030303  0.03030303]
 [ 0.10606061  0.04545455  0.07575758  0.04545455]]


In [28]:
weight_E=np.sum(div_E)
print(weight_E)

1.0
