In [51]:
# Unlike Simple Linear Regression,
# Multiple Linear Regression takes more than 2 different independent variables (features)
# from the data, and predicts Y which is called Response Variable.

# Independet variable = Feature = X varible

# Using <scikit-learn> to generate the matrix X for Multiple Linear Regression

In [52]:
import numpy as np
from sklearn import linear_model
import pandas as pd
from sklearn.metrics import r2_score #R^2 coefficient of determination
from sklearn.model_selection import train_test_split

In [53]:
def main():
    data = pd.read_csv("ad.csv", header = 0)
    response_var = -1
    y_vec = data.ix[:, response_var].as_matrix().reshape(-1,1)
    # as_matrix from pandas;
    # pandas.DataFrame.ix;
    # .ix[] supports mixed integer and label based access. 
    # Oh, Numpy also has ix!
    # numpy.ix(*args)
    ## Construc an open mesh from multiple sequences.
    ## This function takes N 1-D sequences and return N outputs with
    ## N dimensions each.
    
    ### For the Series object, pandas offers three types of addressing.
    ### s.iloc[] -- for inteer position addressing
    ### s.loc[] -- for index label addressing
    ### s.ix[] -- for a hybrid of integer position and label addressing
    
    y_label = data.columns[response_var]
    
    x_label = ", ".join(data.columns[range(1,4)])
    x_mat = data.ix[:,range(1,4)].as_matrix().reshape(-1,3)
    multi_var_adversiting(x_mat, y_vec, x_label)

In [54]:
def ulti_var_advertising(x_mat, y_vec, x_label, rs = 108):
    x_train, x_text, y_train, y_text = train_test_split(x_mat, y_vec,
                                                        test_size = 0.2,
                                                        random_state=rs)
    regr = linear_model.LinearRegression()
    
    reg.fit(x_train, y_train)
    predicted_y_text = regr.predict(x_test)
    print("Independet variables: {}".format(x_label))
    print("Coefficients: {}".format(regr.coef_))
    print("Intercept: {}".format(regr.intercept_))
    print("RSS on test data: {}".format(np.sum((predicted_y_test - y_test)**2)))
    print("R^2 on test data: {}".format(r2_score(y_test, predicted_y_test)))
    print()
    
if __name__ == "__main__":
    main()

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:4: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  after removing the cwd from sys.path.


NameError: name 'multi_var_adversiting' is not defined

In [55]:
from sklearn import datasets

In [56]:
iris = datasets.load_iris()

In [57]:
X = iris.data[:, :4]
Y = iris.target

In [58]:
from sklearn.linear_model import LogisticRegression

In [59]:
import numpy as np

In [60]:
def load_data():
	return datasets.load_iris(return_X_y=True)

In [61]:
print(load_data())

(array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
       [ 

In [62]:
def load_data2():
	return datasets.load_iris(return_X_y=False)

In [63]:
print(load_data2())

{'data': array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2],
       [ 5.4,  3.9,  1.7,  0.4],
       [ 4.6,  3.4,  1.4,  0.3],
       [ 5. ,  3.4,  1.5,  0.2],
       [ 4.4,  2.9,  1.4,  0.2],
       [ 4.9,  3.1,  1.5,  0.1],
       [ 5.4,  3.7,  1.5,  0.2],
       [ 4.8,  3.4,  1.6,  0.2],
       [ 4.8,  3. ,  1.4,  0.1],
       [ 4.3,  3. ,  1.1,  0.1],
       [ 5.8,  4. ,  1.2,  0.2],
       [ 5.7,  4.4,  1.5,  0.4],
       [ 5.4,  3.9,  1.3,  0.4],
       [ 5.1,  3.5,  1.4,  0.3],
       [ 5.7,  3.8,  1.7,  0.3],
       [ 5.1,  3.8,  1.5,  0.3],
       [ 5.4,  3.4,  1.7,  0.2],
       [ 5.1,  3.7,  1.5,  0.4],
       [ 4.6,  3.6,  1. ,  0.2],
       [ 5.1,  3.3,  1.7,  0.5],
       [ 4.8,  3.4,  1.9,  0.2],
       [ 5. ,  3. ,  1.6,  0.2],
       [ 5. ,  3.4,  1.6,  0.4],
       [ 5.2,  3.5,  1.5,  0.2],
       [ 5.2,  3.4,  1.4,  0.2],
       [ 4.7,  3.2,  1.6,  0.2],
 

In [64]:
    lr = LogisticRegression()
    lr.fit(X,Y)
    predicted_p = lr.predict_proba(X) #output

In [65]:
def multi_classification(X, Y):
	# input : X (features), shape:(number of samples, number of features)
	# input : binary_label (1 or 0), shape:(number of samples, )
	# output : probability to belong to that class, shape:(number of samples, 
    lr = LogisticRegression()
    lr.fit(X, Y)
    predicted_p = lr.predict_proba(X) #output
	
    return predicted_p

In [66]:
print(multi_classification(X,Y))

[[  8.79681649e-01   1.20307538e-01   1.08131372e-05]
 [  7.99706325e-01   2.00263292e-01   3.03825365e-05]
 [  8.53796795e-01   1.46177302e-01   2.59031285e-05]
 [  8.25383127e-01   1.74558937e-01   5.79356669e-05]
 [  8.97323628e-01   1.02665167e-01   1.12050036e-05]
 [  9.26986574e-01   7.30004562e-02   1.29693872e-05]
 [  8.95064974e-01   1.04895775e-01   3.92506205e-05]
 [  8.61839691e-01   1.38141399e-01   1.89095833e-05]
 [  8.03156719e-01   1.96758495e-01   8.47861140e-05]
 [  7.95421554e-01   2.04552763e-01   2.56832240e-05]
 [  8.92083069e-01   1.07910759e-01   6.17176870e-06]
 [  8.63364991e-01   1.36600589e-01   3.44201798e-05]
 [  7.88177618e-01   2.11794929e-01   2.74526810e-05]
 [  8.35079702e-01   1.64888155e-01   3.21426418e-05]
 [  9.28349898e-01   7.16491356e-02   9.66254924e-07]
 [  9.64535656e-01   3.54620850e-02   2.25877936e-06]
 [  9.40906153e-01   5.90890027e-02   4.84421830e-06]
 [  8.91740161e-01   1.08245661e-01   1.41772124e-05]
 [  8.96525617e-01   1.03467

In [67]:
values = multi_clasification(X,Y)
for i in values:
    return i.max()
print(values)    

NameError: name 'multi_clasification' is not defined

In [ ]:
print(Y)

In [ ]:
import numpy as np
tmp =[]
for i in multi_classification(X,Y):
    tmp.append((i.max().index())
print(tmp)

In [ ]:
tmp = np.amax(Y,axis=1)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y, Y_pred)
return accuracy