In [1]:
# 1. ndarray? N-dimensional array

In [3]:
# 2. (n,) : tuple, length 1, since (n) indicates sth other than tuple, 
# (n,) one dimensional array wiht a length of one.

In [4]:
# 3 reshape(-1,1): A numpy matrix can be reahepd into a vector using reshape function with parameter
# with parameter -1. 
# newshape: int or tuple of ints.
# if an int, the result would be 1-D array of that length. Since the new shape should be compatible

In [1]:
# with the original shape. One shape dimension can be -1????????
# 4. if __name__ == "__main__": run a module as a script right on the script page

In [2]:
# numpy.random.normal: univariate normal distribution samples

In [3]:
# cov = np.array([[200, x],[y, 200]])
# curious - x and y get diff.? positive, negative, smaller, bigger

In [6]:
# 5. samples[:,1] samples[:,0]
# don't get the meanig of the colon in the bracket.
import numpy as np
from numpy import newaxis

In [9]:
# and what is numpy floor? 
# 6. numpy.floor: returns the floor of the input, element-wise
# if the input were -1.7, then the numpy.floor returns -2.

In [10]:
a = np.floor(10*np.random.random((2,2)))
a

array([[ 2.,  4.],
       [ 4.,  0.]])

In [11]:
# 7. numpy.random.random: return random float in the half open interval (0.0, 1.0)

In [12]:
b = np.floor(10*np.random.random((2,2)))

In [13]:
b

array([[ 2.,  5.],
       [ 0.,  0.]])

In [14]:
np.vstack((a,b))

array([[ 2.,  4.],
       [ 4.,  0.],
       [ 2.,  5.],
       [ 0.,  0.]])

In [16]:
# 8. and what is vstack? vertical stack? stacking vertically? - YES
# Stacking arrays in sequence vertically, row wise.

In [17]:
np.hstack((a,b))

array([[ 2.,  4.,  2.,  5.],
       [ 4.,  0.,  0.,  0.]])

In [18]:
from numpy import newaxis

In [28]:
k =np.column_stack((a,b))
print(k)

[[ 4.  2.]
 [ 2.  8.]]


In [29]:
# and column stack equals to hstack? -Seems like it is.

In [21]:
a = np.array([4.,2.])

In [22]:
b = np.array([2.,8.])

In [23]:
print(a)

[ 4.  2.]


In [24]:
print(b)

[ 2.  8.]


In [25]:
a[:,newaxis]

array([[ 4.],
       [ 2.]])

In [27]:
print(k)

[[ 4.  2.]
 [ 2.  8.]]


In [32]:
c = np.floor(10*np.random.random((2,2)))
d = np.floor(10*np.random.random((2,2)))
df = np.column_stack((c,d))

In [33]:
print(c)
print(d)
print(df)

[[ 4.  2.]
 [ 0.  8.]]
[[ 6.  4.]
 [ 0.  0.]]
[[ 4.  2.  6.  4.]
 [ 0.  8.  0.  0.]]


In [34]:
df[:,1]

array([ 2.,  8.])

In [36]:
df[:,-1]

array([ 4.,  0.])

In [37]:
df[1,:]

array([ 0.,  8.,  0.,  0.])

In [38]:
# 8. and now [::-1] what does this mean?
# the term is to reverse the order.

In [39]:
# 8. numpy.conatenate: join a sequence of array along an existing axis
a = np.array([[1,2],[3,4]])
b = np.array([[7,7,]])
np.concatenate((a,b), axis = 0)
             

array([[1, 2],
       [3, 4],
       [7, 7]])

In [40]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 7],
       [3, 4, 7]])

In [41]:
# 9. numpy.random.normal(loc = 0.0, scale = 1.0, size = None)
# Draw random samples from a normal (Gaussian) distribution
# loc = mean, scale = standard deviation

# 10. numpy.random.uniform(low = 0.0, high = 1.0, size = None)
# low: Lower boundary, high: Upper boundary(excluded), size: Output shape.


In [ ]:
# 11. numpy.ndarray.shape
# tupe of array dimensions
