In [17]:
import pandas as pd
import numpy as np
a = np.zeros((3,3))
print(a)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [18]:
b = a[:]
print(b)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [19]:
a[:,-1] = 3
print(a)

[[ 0.  0.  3.]
 [ 0.  0.  3.]
 [ 0.  0.  3.]]


In [20]:
a[1,:] = 2
print(a)

[[ 0.  0.  3.]
 [ 2.  2.  2.]
 [ 0.  0.  3.]]


In [21]:
r = a.reshape(-1,1)
print(r)

[[ 0.]
 [ 0.]
 [ 3.]
 [ 2.]
 [ 2.]
 [ 2.]
 [ 0.]
 [ 0.]
 [ 3.]]


In [22]:
print(a.reshape(1,-1))

[[ 0.  0.  3.  2.  2.  2.  0.  0.  3.]]
