# Econometrics 2018 Fall, HW1

## 0. 필요한 라이브러리 로드

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
#from IPython.display import display, Math, Latex
import statsmodels.api as sm
from sklearn import linear_model

/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


## 1. 데이터 불러오기, 데이터 프레임으로 형식 변경

In [2]:
with open('mroz_data_workers.txt', 'r') as f:
    x = f.readlines()

In [3]:
col_names = x[0].split(' ')
df = pd.DataFrame(columns = col_names)

In [4]:
only_d = x[1:]

In [5]:
for i in range(len(only_d)):
    only_d[i] = only_d[i].split()

In [6]:
data = pd.DataFrame(only_d,columns = col_names)

In [7]:
data.columns

Index(['LFP', 'WHRS', 'KL6', 'K618', 'WA', 'WE', 'WW', 'RPWG', 'HHRS', 'HA',
       'HE', 'HW', 'FAMINC', 'MTR', 'WMED', 'WFED', 'UN', 'CIT', 'AX\n'],
      dtype='object')

In [8]:
data # 428 rows × 19 columns

LFP  WHRS KL6 K618  WA  WE       WW  RPWG  HHRS  HA  HE       HW FAMINC  \
0     1  1610   1    0  32  12   3.3540  2.65  2708  34  12   4.0288  16310   
1     1  1656   0    2  30  12   1.3889  2.65  2310  30   9   8.4416  21800   
2     1  1980   1    3  35  12   4.5455  4.04  3072  40  12   3.5807  21040   
3     1   456   0    3  34  12   1.0965  3.25  1920  53  10   3.5417   7300   
4     1  1568   1    2  31  14   4.5918  3.60  2000  32  12  10.0000  27300   
5     1  2032   0    0  54  12   4.7421  4.70  1040  57  11   6.7106  19495   
6     1  1440   0    2  37  16   8.3333  5.95  2670  37  12   3.4277  21152   
7     1  1020   0    0  54  12   7.8431  9.98  4120  53   8   2.5485  18900   
8     1  1458   0    2  48  12   2.1262  0.00  1995  52   4   4.2206  20405   
9     1  1600   0    2  39  12   4.6875  4.15  2100  43  12   5.7143  20425   
10    1  1969   0    1  33  12   4.0630  4.30  2450  34  12   9.7959  32300   
11    1  1960   0    1  42  11   4.5918  4.58  2375  47  14   8.0000  28700   
12    1   240   1    2  30  12   2.0833  0.00  2830  33  16   5.3004  15500   
13    1   997   0    2  43  12   2.2668  3.50  3317  46  12   4.3413  16860   
14    1  1848   0    1  43  10   3.6797  3.38  2024  45  17  10.8700  31431   
15    1  1224   0    3  35  11   1.3472  0.00  1694  38  12   9.1499  19180   
16    1  1400   0    2  43  12   3.2143  4.00  2156  45  12   6.1224  18600   
17    1   640   0    5  39  12   5.1750  2.25  2250  40  12   6.1498  19151   
18    1  2000   0    0  45  12   2.0000  2.30  2024  51  11   6.9170  18100   
19    1  1324   0    4  35  12   7.5529  3.94  2123  40  10   4.7103  20300   
20    1  2215   0    2  42  16   3.5052  3.30  4160  48  16   3.1310  30419   
21    1  1680   0    0  30  12   3.5714  3.80  2000  35  12   4.0000  14090   
22    1  1600   0    0  48  13   3.2500  3.26  2420  52  17   7.2227  22679   
23    1   800   0    0  45  12   3.2500  2.20  1150  53  17   7.9652  12160   
24    1  1955   1    1  31  12   2.1545  2.30  2024  31  12   4.0884  12487   
25    1   660   0    2  43  17   3.7879  0.00  1904  43  17  14.1810  29850   
26    1   525   0    0  59  12   4.0000  3.18  2448  53  16   6.5359  18100   
27    1  1904   0    3  32  12   4.7269  6.07  2000  33  13   8.5000  26000   
28    1  1516   1    0  31  17   7.2559  6.00  2390  30  17   6.2762  26100   
29    1   346   0    0  42  12   5.8671  6.39  1920  47  10   5.2083  17730   
..   ..   ...  ..  ...  ..  ..      ...   ...   ...  ..  ..      ...    ...   
398   1  1720   0    1  49  14   1.7442  0.00  2600  45  16   7.2308  42100   
399   1  3533   2    2  38  15   5.0948  8.50  2000  38   9   7.0000  36430   
400   1  2000   0    2  42  14   2.5000  0.00  2218  45  14   7.2137  26000   
401   1   800   0    1  48   8   3.8250  2.30  2000  52   5   4.5000  62060   
402   1  3000   0    0  51  14   1.0000  0.00  2595  53  16   8.8632  28300   
403   1   293   0    2  43  12   3.0717  4.00  2400  47  12   9.3333  24149   
404   1  1872   0    1  43  12   1.7163  0.00  2856  48  12   3.8263  28141   
405   1  2058   0    1  38  12   4.0209  4.00  2601  38  14   5.4448  23057   
406   1  1832   0    1  44  12   5.4585  4.95  2054  48   9   8.7634  28900   
407   1   120   1    3  36  12  25.0000  9.98  2500  35  12   8.4000  24000   
408   1  1632   0    0  38  12   2.3897  2.30  1960  31  12   5.1020  13900   
409   1   778   0    0  47   8   3.2134  7.25  2058  51   8   7.4101  31810   
410   1  1984   0    2  34  12   3.3770  3.14  2410  49  10   5.3527  19840   
411   1   225   1    2  40  17   1.7778  0.00  1278  38  17  19.5620  25490   
412   1  1960   0    1  31  12   3.1633  3.18  2875  35  12   5.0783  20800   
413   1   444   0    0  46  12   2.7027  0.00  2340  49  12   0.5128   2400   
414   1   384   0    3  36  14   1.6927  0.00  3060  43  17   5.4020  32650   
415   1  1170   1    2  39  13   0.2137  0.00  1920  47  12   7.8646  16370   
416   1  1330   0    2  36  17   6.7669  4.50  3390  3

## 2. 분석에 사용할 13개 변수 및 타겟 칼럼 골라내기

In [9]:
col_need = ['LFP','KL6','K618','WA','WE','WW','WMED','WFED','AX\n','HHRS','HA','HE','HW']

In [10]:
len(col_need)

13

In [11]:
d2 = data[col_need]

In [12]:
d2.shape

(428, 13)

In [24]:
#X = d2 # X variable

In [25]:
target = data['WHRS'] #Series
#y = target # y 

## 3. 숙제에 제시된 회귀모형 만들기

$$\forall i = 1,2, \cdots , 428$$
$$WHRS_i = \beta_1 + \beta_2KL6_i + \beta_3K618_i + \beta_4WA_i + \beta_5WE_i
+ \beta_6WW_i + \beta_7WMED_i + \beta_8WFED_i +\beta_9AX_i + \beta_10HHRS_i + \beta_{11} HA_i
+ \beta_{12} HE_i + \beta_{13} HW_i + u_i$$

In [26]:
y = data['WHRS'].reshape(-1,)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  """Entry point for launching an IPython kernel.


In [27]:
y = list(y)

In [28]:
clf = linear_model.LinearRegression()

In [29]:
clf.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [30]:
clf.coef_ # Sklearn library 이용

array([ 0.00000000e+00, -3.20915826e+02, -7.61587201e+01, -1.67975979e+01,
        1.70945953e+00, -2.40304731e+01,  3.33657618e+00, -4.46645039e+00,
        3.00897581e+01, -1.29891434e-02, -3.43151316e+00, -8.06763260e+00,
       -6.94681095e+00])

In [31]:
clf.intercept_

2184.6894400706806

In [86]:
data = data.convert_objects(convert_numeric=True)
y = np.asarray(data['WHRS'])
#print(y.shape)
X = np.asarray(data[['LFP','KL6','K618','WA','WE','WW','WMED','WFED','AX\n','HHRS','HA','HE','HW']]) 
#print(X.shape)
X = sm.add_constant(X)
model = sm.OLS(y, X).fit()
#model.summary()

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use DataFrame.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  


<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.150
Model:                            OLS   Adj. R-squared:                  0.125
Method:                 Least Squares   F-statistic:                     6.086
Date:                Mon, 22 Oct 2018   Prob (F-statistic):           7.35e-10
Time:                        01:17:34   Log-Likelihood:                -3420.2
No. Observations:                 428   AIC:                             6866.
Df Residuals:                     415   BIC:                             6919.
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2184.6894    373.914      5.843      0.000    1449.688    2919.691
x1          -320.9158     97.621     -3.287      0.001    -512.809    -129.022
x2           -76.1587     30.515     -2.496      0.013    -136.142     -16.175
x3           -16.7976     10.826     -1.552      0.122     -38.077       4.482
x4             1.7095     21.599      0.079      0.937     -40.747      44.166
x5           -24.0305     11.497     -2.090      0.037     -46.630      -1.431
x6             3.3366     13.418      0.249      0.804     -23.040      29.713
x7            -4.4665     12.620     -0.354      0.724     -29.274      20.341
x8            30.0898      5.298      5.680      0.000      19.676      40.504
x9            -0.0130      0.067     -0.194      0.846      -0.145       0.119
x10           -3.4315     10.084     -0.340      0.734     -23.253      16.390
x11           -8.0676     15.673     -0.515      0.607     -38.875      22.740
x12           -6.9468     12.091     -0.575      0.566     -30.713      16.820
==============================================================================
Omnibus:                       25.604   Durbin-Watson:                   2.029
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               38.000
Skew:                           0.448   Prob(JB):                     5.60e-09
Kurtosis:                       4.152   Cond. No.                     2.47e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.47e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

## 1. Compute the least squares estimator beta hat
#### * 두 개 서로 다른 라이브러리(sklearn, statsmodels) 이용 결과, 동일한 계수 값 리턴

In [32]:
clf.coef_ #sklearn library 

array([ 0.00000000e+00, -3.20915826e+02, -7.61587201e+01, -1.67975979e+01,
        1.70945953e+00, -2.40304731e+01,  3.33657618e+00, -4.46645039e+00,
        3.00897581e+01, -1.29891434e-02, -3.43151316e+00, -8.06763260e+00,
       -6.94681095e+00])

In [87]:
model.summary() #statsmodel libarary

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.150
Model:                            OLS   Adj. R-squared:                  0.125
Method:                 Least Squares   F-statistic:                     6.086
Date:                Mon, 22 Oct 2018   Prob (F-statistic):           7.35e-10
Time:                        01:19:23   Log-Likelihood:                -3420.2
No. Observations:                 428   AIC:                             6866.
Df Residuals:                     415   BIC:                             6919.
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2184.6894    373.914      5.843      0.000    1449.688    2919.691
x1          -320.9158     97.621     -3.287      0.001    -512.809    -129.022
x2           -76.1587     30.515     -2.496      0.013    -136.142     -16.175
x3           -16.7976     10.826     -1.552      0.122     -38.077       4.482
x4             1.7095     21.599      0.079      0.937     -40.747      44.166
x5           -24.0305     11.497     -2.090      0.037     -46.630      -1.431
x6             3.3366     13.418      0.249      0.804     -23.040      29.713
x7            -4.4665     12.620     -0.354      0.724     -29.274      20.341
x8            30.0898      5.298      5.680      0.000      19.676      40.504
x9            -0.0130      0.067     -0.194      0.846      -0.145       0.119
x10           -3.4315     10.084     -0.340      0.734     -23.253      16.390
x11           -8.0676     15.673     -0.515      0.607     -38.875      22.740
x12           -6.9468     12.091     -0.575      0.566     -30.713      16.820
==============================================================================
Omnibus:                       25.604   Durbin-Watson:                   2.029
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               38.000
Skew:                           0.448   Prob(JB):                     5.60e-09
Kurtosis:                       4.152   Cond. No.                     2.47e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.47e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

## 2. Estimate the variance-covariance matrix of beta hat, and var(beta hat)

In [94]:
cov_mat = model.cov_params()
cov_mat.shape

(13, 13)

In [95]:
cov_mat

array([[ 1.39811609e+05, -8.73850140e+03, -4.09287291e+03,
        -6.19405665e+02, -2.31059022e+03,  2.11129499e+02,
        -9.85432109e+02,  1.16760347e+02, -5.77774484e+01,
        -8.86385779e+00, -9.28513444e+02, -3.91544923e+02,
        -3.07855563e+02],
       [-8.73850140e+03,  9.52988147e+03,  1.07203366e+02,
         5.25582848e+01, -2.15277061e+02, -7.84700238e+00,
         9.09420023e+01, -1.35529013e+01,  2.97466242e+01,
         6.79628426e-01,  1.18432890e+02, -6.20980741e+01,
         9.13746979e+01],
       [-4.09287291e+03,  1.07203366e+02,  9.31179161e+02,
         4.26567896e+01,  4.37460053e+01,  8.72791982e+00,
        -1.31504301e+01,  3.24374622e+01,  3.80168698e+01,
        -1.81290708e-01,  3.71780653e+00,  1.18252457e+01,
        -1.83290882e+01],
       [-6.19405665e+02,  5.25582848e+01,  4.26567896e+01,
         1.17193602e+02,  3.52835283e+00,  2.42522290e+00,
         6.97003971e+00,  7.04616492e+00, -1.39709156e+01,
        -2.10174160e-02, -9.19178112e

## Compute the standard error of beta hat

In [96]:
model.bse

array([3.73913906e+02, 9.76211118e+01, 3.05152283e+01, 1.08255994e+01,
       2.15987570e+01, 1.14970076e+01, 1.34184891e+01, 1.26203241e+01,
       5.29778086e+00, 6.70132533e-02, 1.00837597e+01, 1.56725090e+01,
       1.20905760e+01])

## 4.Compute the t-values for $$ H_0 : \beta_j = 0,  (\forall j= 1,2, ...,13).$$

In [112]:
model.params

array([ 2.18468944e+03, -3.20915826e+02, -7.61587201e+01, -1.67975979e+01,
        1.70945953e+00, -2.40304731e+01,  3.33657618e+00, -4.46645039e+00,
        3.00897581e+01, -1.29891434e-02, -3.43151316e+00, -8.06763260e+00,
       -6.94681095e+00])

In [116]:
model.tvalues

array([ 5.84276061, -3.2873609 , -2.49576111, -1.55165522,  0.0791462 ,
       -2.09015023,  0.24865513, -0.35390933,  5.67969097, -0.19382947,
       -0.34030097, -0.51476331, -0.5745641 ])

In [117]:
model.pvalues

array([1.03890260e-08, 1.09737321e-03, 1.29560143e-02, 1.21506983e-01,
       9.36954486e-01, 3.72123888e-02, 8.03750563e-01, 7.23586571e-01,
       2.54156773e-08, 8.46404248e-01, 7.33802074e-01, 6.06992470e-01,
       5.65897452e-01])