# Econometrics 2018 Fall, HW1
### 2018321078 정유진
<br>

## 0. 필요한 라이브러리 로드

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
#from IPython.display import display, Math, Latex
import statsmodels.api as sm
from sklearn import linear_model

/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools


## 1. 데이터 불러오기, 데이터 프레임으로 형식 변경

In [2]:
with open('mroz_data_workers.txt', 'r') as f:
    x = f.readlines()

In [3]:
col_names = x[0].split(' ')
df = pd.DataFrame(columns = col_names)

In [4]:
only_d = x[1:]

In [5]:
for i in range(len(only_d)):
    only_d[i] = only_d[i].split()

In [6]:
data = pd.DataFrame(only_d,columns = col_names)

In [7]:
data.columns

Index(['LFP', 'WHRS', 'KL6', 'K618', 'WA', 'WE', 'WW', 'RPWG', 'HHRS', 'HA',
       'HE', 'HW', 'FAMINC', 'MTR', 'WMED', 'WFED', 'UN', 'CIT', 'AX\n'],
      dtype='object')

In [8]:
data.head() # 428 rows × 19 columns

LFP  WHRS KL6 K618  WA  WE      WW  RPWG  HHRS  HA  HE       HW FAMINC  \
0   1  1610   1    0  32  12  3.3540  2.65  2708  34  12   4.0288  16310   
1   1  1656   0    2  30  12  1.3889  2.65  2310  30   9   8.4416  21800   
2   1  1980   1    3  35  12  4.5455  4.04  3072  40  12   3.5807  21040   
3   1   456   0    3  34  12  1.0965  3.25  1920  53  10   3.5417   7300   
4   1  1568   1    2  31  14  4.5918  3.60  2000  32  12  10.0000  27300   

     MTR WMED WFED    UN CIT AX\n  
0  .7215   12    7   5.0   0   14  
1  .6615    7    7  11.0   1    5  
2  .6915   12    7   5.0   0   15  
3  .7815    7    7   5.0   0    6  
4  .6215   12   14   9.5   1    7

In [9]:
data.sample(5)

LFP  WHRS KL6 K618  WA  WE      WW  RPWG  HHRS  HA  HE       HW FAMINC  \
161   1   993   0    2  37  16  5.0352  8.30  2739  39  17   9.8576  32300   
355   1    63   1    2  35  16  3.9683  0.00  2385  37  16   9.6436  23750   
392   1  1664   0    0  50  12  1.2019  5.00  3120  54  13   1.3013  16500   
121   1  2058   0    0  41  11  2.9310  2.90  1984  42  12   4.7883  15652   
309   1  1600   0    1  40  12  3.7500  3.30  1920  39  12  11.4580  29150   

       MTR WMED WFED    UN CIT AX\n  
161  .5815   12   16  14.0   1    9  
355  .6615   14    7  14.0   1    7  
392  .7215    7    7   7.5   0   11  
121  .7215   12   12   7.5   0   23  
309  .5815   12    7   7.5   1    8

## 2. 분석에 사용할 13개 변수 및 타겟 칼럼 골라내기

In [10]:
col_need = ['LFP','KL6','K618','WA','WE','WW','WMED','WFED','AX\n','HHRS','HA','HE','HW']

In [11]:
len(col_need)

13

In [12]:
d2 = data[col_need]

In [13]:
d2.shape

(428, 13)

In [14]:
X = d2 # X variable

In [15]:
target = data['WHRS'] #Series
#y = target # y 

## 3. 숙제에 제시된 회귀모형 만들기

$$\forall i = 1,2, \cdots , 428$$
$$WHRS_i = \beta_1 + \beta_2KL6_i + \beta_3K618_i + \beta_4WA_i + \beta_5WE_i
+ \beta_6WW_i + \beta_7WMED_i + \beta_8WFED_i +\beta_9AX_i + \beta_10HHRS_i + \beta_{11} HA_i
+ \beta_{12} HE_i + \beta_{13} HW_i + u_i$$

In [16]:
y = data['WHRS'].reshape(-1,)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  """Entry point for launching an IPython kernel.


In [17]:
y = list(y)

In [18]:
clf = linear_model.LinearRegression()

In [19]:
clf.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [20]:
clf.coef_ # Sklearn library 이용

array([ 0.00000000e+00, -3.20915826e+02, -7.61587201e+01, -1.67975979e+01,
        1.70945953e+00, -2.40304731e+01,  3.33657618e+00, -4.46645039e+00,
        3.00897581e+01, -1.29891434e-02, -3.43151316e+00, -8.06763260e+00,
       -6.94681095e+00])

In [21]:
clf.intercept_

2184.6894400706806

In [22]:
data = data.convert_objects(convert_numeric=True)
y = np.asarray(data['WHRS'])
#print(y.shape)
X = np.asarray(data[['LFP','KL6','K618','WA','WE','WW','WMED','WFED','AX\n','HHRS','HA','HE','HW']]) 
#print(X.shape)
X = sm.add_constant(X)
model = sm.OLS(y, X).fit()
#model.summary()

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: convert_objects is deprecated.  To re-infer data dtypes for object columns, use DataFrame.infer_objects()
For all other conversions use the data-type specific converters pd.to_datetime, pd.to_timedelta and pd.to_numeric.
  """Entry point for launching an IPython kernel.


## 1. Compute the least squares estimator beta hat

In [27]:
model.params

array([ 2.18468944e+03, -3.20915826e+02, -7.61587201e+01, -1.67975979e+01,
        1.70945953e+00, -2.40304731e+01,  3.33657618e+00, -4.46645039e+00,
        3.00897581e+01, -1.29891434e-02, -3.43151316e+00, -8.06763260e+00,
       -6.94681095e+00])

In [28]:
model.summary() #statsmodel libarary

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.150
Model:                            OLS   Adj. R-squared:                  0.125
Method:                 Least Squares   F-statistic:                     6.086
Date:                Mon, 22 Oct 2018   Prob (F-statistic):           7.35e-10
Time:                        17:49:20   Log-Likelihood:                -3420.2
No. Observations:                 428   AIC:                             6866.
Df Residuals:                     415   BIC:                             6919.
Df Model:                          12                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2184.6894    373.914      5.843      0.000    1449.688    2919.691
x1          -320.9158     97.621     -3.287      0.001    -512.809    -129.022
x2           -76.1587     30.515     -2.496      0.013    -136.142     -16.175
x3           -16.7976     10.826     -1.552      0.122     -38.077       4.482
x4             1.7095     21.599      0.079      0.937     -40.747      44.166
x5           -24.0305     11.497     -2.090      0.037     -46.630      -1.431
x6             3.3366     13.418      0.249      0.804     -23.040      29.713
x7            -4.4665     12.620     -0.354      0.724     -29.274      20.341
x8            30.0898      5.298      5.680      0.000      19.676      40.504
x9            -0.0130      0.067     -0.194      0.846      -0.145       0.119
x10           -3.4315     10.084     -0.340      0.734     -23.253      16.390
x11           -8.0676     15.673     -0.515      0.607     -38.875      22.740
x12           -6.9468     12.091     -0.575      0.566     -30.713      16.820
==============================================================================
Omnibus:                       25.604   Durbin-Watson:                   2.029
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               38.000
Skew:                           0.448   Prob(JB):                     5.60e-09
Kurtosis:                       4.152   Cond. No.                     2.47e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.47e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

## 2. Estimate the variance-covariance matrix of beta hat, and var(beta hat)

In [29]:
cov_mat = model.cov_params()
cov_mat.shape

(13, 13)

In [30]:
cov_mat

array([[ 1.39811609e+05, -8.73850140e+03, -4.09287291e+03,
        -6.19405665e+02, -2.31059022e+03,  2.11129499e+02,
        -9.85432109e+02,  1.16760347e+02, -5.77774484e+01,
        -8.86385779e+00, -9.28513444e+02, -3.91544923e+02,
        -3.07855563e+02],
       [-8.73850140e+03,  9.52988147e+03,  1.07203366e+02,
         5.25582848e+01, -2.15277061e+02, -7.84700238e+00,
         9.09420023e+01, -1.35529013e+01,  2.97466242e+01,
         6.79628426e-01,  1.18432890e+02, -6.20980741e+01,
         9.13746979e+01],
       [-4.09287291e+03,  1.07203366e+02,  9.31179161e+02,
         4.26567896e+01,  4.37460053e+01,  8.72791982e+00,
        -1.31504301e+01,  3.24374622e+01,  3.80168698e+01,
        -1.81290708e-01,  3.71780653e+00,  1.18252457e+01,
        -1.83290882e+01],
       [-6.19405665e+02,  5.25582848e+01,  4.26567896e+01,
         1.17193602e+02,  3.52835283e+00,  2.42522290e+00,
         6.97003971e+00,  7.04616492e+00, -1.39709156e+01,
        -2.10174160e-02, -9.19178112e

## Compute the standard error of beta hat

In [31]:
model.bse

array([3.73913906e+02, 9.76211118e+01, 3.05152283e+01, 1.08255994e+01,
       2.15987570e+01, 1.14970076e+01, 1.34184891e+01, 1.26203241e+01,
       5.29778086e+00, 6.70132533e-02, 1.00837597e+01, 1.56725090e+01,
       1.20905760e+01])

## 4.Compute the t-values for $$ H_0 : \beta_j = 0,  (\forall j= 1,2, ...,13).$$

In [32]:
model.tvalues

array([ 5.84276061, -3.2873609 , -2.49576111, -1.55165522,  0.0791462 ,
       -2.09015023,  0.24865513, -0.35390933,  5.67969097, -0.19382947,
       -0.34030097, -0.51476331, -0.5745641 ])

In [33]:
model.pvalues

array([1.03890260e-08, 1.09737321e-03, 1.29560143e-02, 1.21506983e-01,
       9.36954486e-01, 3.72123888e-02, 8.03750563e-01, 7.23586571e-01,
       2.54156773e-08, 8.46404248e-01, 7.33802074e-01, 6.06992470e-01,
       5.65897452e-01])